# fly.toml app configuration file generated for stackflow-back on 2025-04-03T17:34:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stackflow-back'
primary_region = 'fra'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
